[package]
name = "rust-fish"
version = "0.1.0"
authors = ["Victor \"ZoroXV\" LE CORRE <victor.le-corre@epita.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
